version: '3'
services:
  dashboard:
    image: netbirdio/dashboard:latest
    restart: always
    ports:
      - "127.0.0.1:7070:80"
    environment:
      - LETSENCRYPT_DOMAIN=none

  netbird-server:
    image: netbirdio/netbird-server:latest
    restart: always
    ports:
      - "127.0.0.1:7071:80"
      - "3478:3478/udp" # STUN
    volumes:
      - netbird_data:/var/lib/netbird
      - ./config.yaml:/etc/netbird/config.yaml
    command: ["--config", "/etc/netbird/config.yaml"]

volumes:
  netbird_data:

